### ISSUE TITLE
Not using browser version of "randombytes" package breaks web bundle

### ISSUE THREAD

**Issue by andria-dev** [crypto-browserify/diffie-hellman#34]
https://github.com/crypto-browserify/diffie-hellman/blob/d795c01543385196e44f6d8218ba6f9b5621d4b0/lib/generatePrime.js#L1

This should be:

```js
var randomBytes = require('randombytes/browser');
```

This way when this code is `require()`ed (which only happens when using the browser module) it won't create a dependency for the Node built-in package "crypto".

**Comment by calvinmetcalf** [comment]
random bytes has a browser field in it's package.json which causes that to happen automatically
